"""One-shot migration: copy a SQLite snapshot into the Postgres + pgvector
schema that Alembic just provisioned.

Strategy:
    Only rows whose FK chain reaches a live project are copied — orphans
    from previously-deleted projects are dropped on the floor. Embeddings
    are NOT carried over (Chroma → pgvector requires re-embedding via the
    new embedder); chunks land with embedding=NULL and `embedded=False`
    so the indexer picks them up on next run.

Tables copied (in FK-safe order):
    projects, documents, document_pages, page_extractions,
    extracted_schedules / notes / cross_references / entities,
    chunks, project_profiles, trade_division_relevance,
    llm_calls (project-scoped), audit_log, app_settings.

Tables intentionally SKIPPED:
    scope_extraction_runs and everything downstream
    (scope_items, scope_citations, trade_packages, scope_conflicts,
    scope_gaps, bid_*). These were generated by the previous pipeline and
    are missing the new evidence_type / link_judge / bilateral / package
    population. Re-running scope extraction (which is now end-to-end on
    Postgres + pgvector with the full Stage 1-11 pipeline) regenerates
    them with proper data.

Usage:
    .venv/bin/python -m scripts.migrate_sqlite_to_postgres
"""

from __future__ import annotations

import asyncio
import json
import logging
from datetime import datetime, timezone
from typing import Any

from sqlalchemy import select, text
from sqlalchemy.ext.asyncio import (
    AsyncSession,
    async_sessionmaker,
    create_async_engine,
)

from app.config import settings
from app.database import Base
from app import models  # noqa: F401  registers all models

log = logging.getLogger(__name__)
logging.basicConfig(level=logging.INFO, format="%(asctime)s %(message)s")


SQLITE_URL = "sqlite+aiosqlite:///./data/app.db"
POSTGRES_URL = settings.database_url


# Order matters: parents before children. Copy in dependency-sorted order.
COPY_ORDER: list[str] = [
    "app_settings",
    "projects",
    "documents",
    "document_pages",
    "page_extractions",
    "extracted_schedules",
    "extracted_notes",
    "extracted_cross_references",
    "extracted_entities",
    "chunks",
    "project_profiles",
    "trade_division_relevance",
    "llm_calls",
    "audit_log",
]


# Columns to NULL out (e.g., chunk.embedding — pgvector column with no
# SQLite source data; will be re-populated by the embedder).
NULL_COLUMNS_BY_TABLE: dict[str, set[str]] = {
    "chunks": {"embedding"},
}


# Boolean columns that need conversion from SQLite's 0/1 INTEGER to bool
# before insert into Postgres BOOLEAN columns. SQLAlchemy core handles
# most of this, but JSON-stored fields don't always.
def _row_to_dict(row: Any, columns: list[str]) -> dict[str, Any]:
    return {col: getattr(row, col) for col in columns}


async def _live_project_ids(sqlite_session: AsyncSession) -> set[str]:
    rows = (await sqlite_session.execute(text("SELECT id FROM projects"))).all()
    return {r[0] for r in rows}


# Maps each table to (fk_column, parent_table) pairs that need to be in the
# live-id sets we accumulate as we walk the dependency tree. Anything not
# listed here only needs project_id filtering.
FK_CHAINS: dict[str, list[tuple[str, str]]] = {
    "document_pages":             [("document_id", "documents")],
    "page_extractions":           [("document_id", "documents"), ("page_id", "document_pages")],
    "extracted_schedules":        [("page_extraction_id", "page_extractions")],
    "extracted_notes":            [("page_extraction_id", "page_extractions")],
    "extracted_cross_references": [("page_extraction_id", "page_extractions")],
    "extracted_entities":         [("page_extraction_id", "page_extractions")],
    "chunks":                     [("document_id", "documents")],
    "llm_calls":                  [],  # has no project FK constraint to enforce
    "audit_log":                  [],  # has project_id and we filter on that already
}


async def _sqlite_columns(sq: AsyncSession, table_name: str) -> set[str]:
    """Inspect SQLite to find which columns actually exist."""
    rows = (await sq.execute(text(f"PRAGMA table_info({table_name})"))).all()
    return {r[1] for r in rows}


async def _copy_table(
    table_name: str,
    sqlite_session: AsyncSession,
    pg_session: AsyncSession,
    live_project_ids: set[str],
    live_ids_by_table: dict[str, set[str]],
) -> int:
    table = Base.metadata.tables[table_name]
    model_columns = [c.name for c in table.columns]
    null_cols = NULL_COLUMNS_BY_TABLE.get(table_name, set())

    # Only SELECT columns that exist in BOTH the model and the SQLite source.
    # Columns the model has but SQLite doesn't (e.g. chunks.embedding) get
    # NULL in Postgres; columns SQLite has but the model dropped get ignored.
    sqlite_cols = await _sqlite_columns(sqlite_session, table_name)
    column_names = [c for c in model_columns if c in sqlite_cols]
    missing_in_sqlite = [c for c in model_columns if c not in sqlite_cols]
    if missing_in_sqlite:
        log.info(
            "%-30s skipping %d new columns (NULL in dest): %s",
            table_name, len(missing_in_sqlite), missing_in_sqlite,
        )

    # Build a SELECT against SQLite for the columns we need
    select_sql = f"SELECT {', '.join(column_names)} FROM {table_name}"
    rows = (await sqlite_session.execute(text(select_sql))).mappings().all()

    if not rows:
        log.info("%-30s 0 rows (empty)", table_name)
        return 0

    # FK filtering: drop rows whose project_id is not in live_project_ids
    if "project_id" in column_names and table_name != "projects":
        rows = [r for r in rows if r["project_id"] in live_project_ids]

    # Multi-hop FK filtering: also drop rows whose parent FK target isn't
    # in the live set we've already loaded. Catches orphan document_pages,
    # page_extractions, chunks, etc. from previously-deleted projects whose
    # children weren't cascade-cleaned.
    for fk_col, parent_table in FK_CHAINS.get(table_name, []):
        parent_live = live_ids_by_table.get(parent_table)
        if parent_live is None:
            continue
        before = len(rows)
        rows = [r for r in rows if r[fk_col] is None or r[fk_col] in parent_live]
        dropped = before - len(rows)
        if dropped:
            log.info(
                "%-30s dropped %d orphan rows (parent %s missing)",
                table_name, dropped, parent_table,
            )

    # NULL-out columns that don't transfer (e.g. embedding)
    if null_cols:
        rows = [
            {**dict(r), **{c: None for c in null_cols if c in r}} for r in rows
        ]
    else:
        rows = [dict(r) for r in rows]

    # Coerce JSON columns: SQLite returns them as strings; Postgres JSON
    # column wants Python dict/list. Detect JSON columns by SQLAlchemy type.
    json_cols = [
        c.name for c in table.columns
        if str(c.type).upper() in ("JSON", "JSONB")
    ]
    if json_cols:
        for row in rows:
            for col in json_cols:
                v = row.get(col)
                if isinstance(v, str):
                    try:
                        row[col] = json.loads(v)
                    except (TypeError, ValueError):
                        row[col] = None

    # Boolean columns: SQLite stores 0/1; psycopg/asyncpg + SQLAlchemy
    # boolean accepts 0/1 fine, but let's normalize to be safe.
    bool_cols = [
        c.name for c in table.columns if str(c.type).upper() == "BOOLEAN"
    ]
    if bool_cols:
        for row in rows:
            for col in bool_cols:
                v = row.get(col)
                if v is not None:
                    row[col] = bool(v)

    # Datetime columns: SQLite stores them as ISO-8601 strings; asyncpg
    # for Postgres requires actual datetime instances. Coerce.
    dt_cols = [
        c.name
        for c in table.columns
        if "DATETIME" in str(c.type).upper() or "TIMESTAMP" in str(c.type).upper()
    ]
    if dt_cols:
        for row in rows:
            for col in dt_cols:
                v = row.get(col)
                if isinstance(v, str):
                    # SQLite ISO format: "2026-05-06 03:21:27.765548" or
                    # "2026-05-06T03:21:27.765548+00:00". Try fromisoformat
                    # first (3.11+ accepts both).
                    s = v.replace("T", " ")
                    try:
                        dt = datetime.fromisoformat(s)
                    except ValueError:
                        # Fall back to a couple of well-known formats
                        dt = None
                        for fmt in (
                            "%Y-%m-%d %H:%M:%S.%f",
                            "%Y-%m-%d %H:%M:%S",
                            "%Y-%m-%d",
                        ):
                            try:
                                dt = datetime.strptime(s, fmt)
                                break
                            except ValueError:
                                continue
                    if dt is None:
                        log.warning(
                            "Could not parse datetime %r in %s.%s; setting NULL",
                            v, table_name, col,
                        )
                        row[col] = None
                    else:
                        # Postgres TIMESTAMP WITH TIME ZONE wants tz-aware;
                        # add UTC if SQLite stored it naive.
                        if dt.tzinfo is None:
                            dt = dt.replace(tzinfo=timezone.utc)
                        row[col] = dt

    # Bulk insert into Postgres
    if rows:
        await pg_session.execute(table.insert(), rows)
        await pg_session.commit()

    # Track surviving IDs so child tables can use them for orphan filtering
    if "id" in column_names:
        live_ids_by_table.setdefault(table_name, set()).update(
            r["id"] for r in rows if r.get("id") is not None
        )

    log.info("%-30s %d rows copied", table_name, len(rows))
    return len(rows)


async def _reset_sequences(pg_session: AsyncSession) -> None:
    """Postgres sequences need to be advanced past the migrated max-id for
    INTEGER PK tables. Our schema uses UUID strings as PKs everywhere, so
    no sequence resets are actually needed. This function is a placeholder
    in case future tables introduce SERIAL/IDENTITY columns.
    """
    pass


async def main() -> None:
    log.info("Connecting to SQLite: %s", SQLITE_URL)
    sqlite_engine = create_async_engine(SQLITE_URL, echo=False, future=True)
    sqlite_session_maker = async_sessionmaker(
        sqlite_engine, class_=AsyncSession, expire_on_commit=False
    )

    log.info("Connecting to Postgres: %s", POSTGRES_URL)
    pg_engine = create_async_engine(POSTGRES_URL, echo=False, future=True)
    pg_session_maker = async_sessionmaker(
        pg_engine, class_=AsyncSession, expire_on_commit=False
    )

    total_copied = 0
    live_ids_by_table: dict[str, set[str]] = {}
    async with sqlite_session_maker() as sq, pg_session_maker() as pg:
        live_ids = await _live_project_ids(sq)
        log.info("Live projects in SQLite: %s", live_ids)

        for table_name in COPY_ORDER:
            if table_name not in Base.metadata.tables:
                log.warning(
                    "Table %s not in current models; skipping (probably "
                    "removed or renamed since SQLite was written)",
                    table_name,
                )
                continue
            n = await _copy_table(table_name, sq, pg, live_ids, live_ids_by_table)
            total_copied += n

        await _reset_sequences(pg)

    await sqlite_engine.dispose()
    await pg_engine.dispose()

    log.info("Done. %d total rows copied to Postgres.", total_copied)


if __name__ == "__main__":
    asyncio.run(main())
