"""P2: sheet_index master manifest table

Revision ID: 0997ae283649
Revises: 0bce48a16238
Create Date: 2026-05-06 00:30:33.354934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0997ae283649'
down_revision: Union[str, Sequence[str], None] = '0bce48a16238'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sheet_index',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('sheet_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('discipline', sa.String(length=32), nullable=True),
    sa.Column('set_order', sa.Integer(), nullable=True),
    sa.Column('revision', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'sheet_id', name='uq_sheet_index_doc_sheet')
    )
    op.create_index(op.f('ix_sheet_index_discipline'), 'sheet_index', ['discipline'], unique=False)
    op.create_index(op.f('ix_sheet_index_document_id'), 'sheet_index', ['document_id'], unique=False)
    op.create_index(op.f('ix_sheet_index_project_id'), 'sheet_index', ['project_id'], unique=False)
    op.create_index(op.f('ix_sheet_index_sheet_id'), 'sheet_index', ['sheet_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sheet_index_sheet_id'), table_name='sheet_index')
    op.drop_index(op.f('ix_sheet_index_project_id'), table_name='sheet_index')
    op.drop_index(op.f('ix_sheet_index_document_id'), table_name='sheet_index')
    op.drop_index(op.f('ix_sheet_index_discipline'), table_name='sheet_index')
    op.drop_table('sheet_index')
    # ### end Alembic commands ###
