"""initial schema

Revision ID: 683b94d07af4
Revises: 
Create Date: 2026-05-05 23:45:33.517727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = '683b94d07af4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value_json', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('llm_calls',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('document_id', sa.String(length=36), nullable=True),
    sa.Column('page_extraction_id', sa.String(length=36), nullable=True),
    sa.Column('purpose', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('cache_read_tokens', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_calls_document_id'), 'llm_calls', ['document_id'], unique=False)
    op.create_index(op.f('ix_llm_calls_page_extraction_id'), 'llm_calls', ['page_extraction_id'], unique=False)
    op.create_index(op.f('ix_llm_calls_project_id'), 'llm_calls', ['project_id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('lifecycle_state', sa.String(length=32), nullable=False),
    sa.Column('trust_score_latest', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=True),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('actor', sa.String(length=128), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_action'), 'audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_audit_log_created_at'), 'audit_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_log_entity_id'), 'audit_log', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_log_entity_type'), 'audit_log', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_log_project_id'), 'audit_log', ['project_id'], unique=False)
    op.create_index(op.f('ix_audit_log_run_id'), 'audit_log', ['run_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('content_type', sa.String(length=255), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('storage_path', sa.String(length=1024), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('vendor_name', sa.String(length=255), nullable=True),
    sa.Column('canonical_vendor', sa.String(length=255), nullable=True),
    sa.Column('vendor_provenance', sa.JSON(), nullable=True),
    sa.Column('doc_type', sa.String(length=64), nullable=True),
    sa.Column('classification_confidence', sa.Float(), nullable=True),
    sa.Column('classification_reasoning', sa.Text(), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('processing_status', sa.String(length=32), nullable=False),
    sa.Column('processing_error', sa.Text(), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_canonical_vendor'), 'documents', ['canonical_vendor'], unique=False)
    op.create_index(op.f('ix_documents_project_id'), 'documents', ['project_id'], unique=False)
    op.create_index(op.f('ix_documents_sha256'), 'documents', ['sha256'], unique=False)
    op.create_index(op.f('ix_documents_source'), 'documents', ['source'], unique=False)
    op.create_index(op.f('ix_documents_vendor_name'), 'documents', ['vendor_name'], unique=False)
    op.create_table('project_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('building_type', sa.String(length=255), nullable=True),
    sa.Column('size_sf', sa.Float(), nullable=True),
    sa.Column('occupancy', sa.String(length=64), nullable=True),
    sa.Column('construction_type', sa.String(length=64), nullable=True),
    sa.Column('sprinklered', sa.Boolean(), nullable=True),
    sa.Column('stories', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('project_number', sa.String(length=64), nullable=True),
    sa.Column('codes', sa.JSON(), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('raw_response', sa.JSON(), nullable=True),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', name='uq_project_profile')
    )
    op.create_index(op.f('ix_project_profiles_project_id'), 'project_profiles', ['project_id'], unique=False)
    op.create_table('scope_extraction_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('sections_total', sa.Integer(), nullable=False),
    sa.Column('sections_completed', sa.Integer(), nullable=False),
    sa.Column('sections_failed', sa.Integer(), nullable=False),
    sa.Column('candidates_generated', sa.Integer(), nullable=False),
    sa.Column('items_validated', sa.Integer(), nullable=False),
    sa.Column('items_after_dedupe', sa.Integer(), nullable=False),
    sa.Column('total_cost_usd', sa.Float(), nullable=False),
    sa.Column('total_latency_ms', sa.Integer(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('trust_score', sa.Float(), nullable=True),
    sa.Column('trust_score_components', sa.JSON(), nullable=True),
    sa.Column('bilateral_coverage_rate', sa.Float(), nullable=True),
    sa.Column('link_judge_pass_rate', sa.Float(), nullable=True),
    sa.Column('spec_section_coverage_rate', sa.Float(), nullable=True),
    sa.Column('conflict_count', sa.Integer(), nullable=True),
    sa.Column('gap_count', sa.Integer(), nullable=True),
    sa.Column('package_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scope_extraction_runs_project_id'), 'scope_extraction_runs', ['project_id'], unique=False)
    op.create_table('trade_division_relevance',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('csi_division', sa.String(length=8), nullable=False),
    sa.Column('division_label', sa.String(length=255), nullable=False),
    sa.Column('is_relevant', sa.Boolean(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('operator_override', sa.Boolean(), nullable=False),
    sa.Column('override_value', sa.Boolean(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'csi_division', name='uq_proj_div')
    )
    op.create_index(op.f('ix_trade_division_relevance_csi_division'), 'trade_division_relevance', ['csi_division'], unique=False)
    op.create_index(op.f('ix_trade_division_relevance_project_id'), 'trade_division_relevance', ['project_id'], unique=False)
    op.create_table('bid_extraction_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('scope_run_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('bids_total', sa.Integer(), nullable=False),
    sa.Column('bids_extracted', sa.Integer(), nullable=False),
    sa.Column('coverage_pairs_total', sa.Integer(), nullable=False),
    sa.Column('coverage_pairs_completed', sa.Integer(), nullable=False),
    sa.Column('total_cost_usd', sa.Float(), nullable=False),
    sa.Column('total_latency_ms', sa.Integer(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scope_run_id'], ['scope_extraction_runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bid_extraction_runs_project_id'), 'bid_extraction_runs', ['project_id'], unique=False)
    op.create_index(op.f('ix_bid_extraction_runs_scope_run_id'), 'bid_extraction_runs', ['scope_run_id'], unique=False)
    op.create_table('document_pages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.String(length=1024), nullable=False),
    sa.Column('thumbnail_path', sa.String(length=1024), nullable=False),
    sa.Column('text_content', sa.Text(), nullable=True),
    sa.Column('text_source', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'page_number', name='uq_doc_page')
    )
    op.create_index(op.f('ix_document_pages_document_id'), 'document_pages', ['document_id'], unique=False)
    op.create_table('scope_conflicts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('conflict_type', sa.String(length=32), nullable=False),
    sa.Column('csi_division', sa.String(length=8), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('arbitrated_value', sa.JSON(), nullable=True),
    sa.Column('arbitration_reasoning', sa.Text(), nullable=True),
    sa.Column('arbitrator', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['scope_extraction_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scope_conflicts_conflict_type'), 'scope_conflicts', ['conflict_type'], unique=False)
    op.create_index(op.f('ix_scope_conflicts_csi_division'), 'scope_conflicts', ['csi_division'], unique=False)
    op.create_index(op.f('ix_scope_conflicts_project_id'), 'scope_conflicts', ['project_id'], unique=False)
    op.create_index(op.f('ix_scope_conflicts_run_id'), 'scope_conflicts', ['run_id'], unique=False)
    op.create_index(op.f('ix_scope_conflicts_status'), 'scope_conflicts', ['status'], unique=False)
    op.create_table('scope_gaps',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('gap_type', sa.String(length=48), nullable=False),
    sa.Column('csi_division', sa.String(length=8), nullable=True),
    sa.Column('csi_section', sa.String(length=16), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('suggested_remediation', sa.Text(), nullable=True),
    sa.Column('related_item_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['scope_extraction_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scope_gaps_csi_division'), 'scope_gaps', ['csi_division'], unique=False)
    op.create_index(op.f('ix_scope_gaps_gap_type'), 'scope_gaps', ['gap_type'], unique=False)
    op.create_index(op.f('ix_scope_gaps_project_id'), 'scope_gaps', ['project_id'], unique=False)
    op.create_index(op.f('ix_scope_gaps_run_id'), 'scope_gaps', ['run_id'], unique=False)
    op.create_index(op.f('ix_scope_gaps_severity'), 'scope_gaps', ['severity'], unique=False)
    op.create_index(op.f('ix_scope_gaps_status'), 'scope_gaps', ['status'], unique=False)
    op.create_table('scope_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('csi_code', sa.String(length=16), nullable=False),
    sa.Column('csi_division', sa.String(length=8), nullable=False),
    sa.Column('division_label', sa.String(length=255), nullable=False),
    sa.Column('section_title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('specification', sa.Text(), nullable=True),
    sa.Column('quantity', sa.String(length=64), nullable=True),
    sa.Column('unit', sa.String(length=16), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('extraction_method', sa.String(length=32), nullable=True),
    sa.Column('qty_confidence', sa.String(length=16), nullable=True),
    sa.Column('qty_provenance', sa.JSON(), nullable=True),
    sa.Column('verifier_status', sa.String(length=16), nullable=True),
    sa.Column('verifier_review', sa.JSON(), nullable=True),
    sa.Column('evidence_tier', sa.String(length=32), nullable=True),
    sa.Column('bilateral_evidence', sa.Boolean(), nullable=True),
    sa.Column('trust_components', sa.JSON(), nullable=True),
    sa.Column('package_id', sa.String(length=36), nullable=True),
    sa.Column('raw_extractions', sa.JSON(), nullable=True),
    sa.Column('validation_votes', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['scope_extraction_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scope_items_csi_code'), 'scope_items', ['csi_code'], unique=False)
    op.create_index(op.f('ix_scope_items_csi_division'), 'scope_items', ['csi_division'], unique=False)
    op.create_index(op.f('ix_scope_items_evidence_tier'), 'scope_items', ['evidence_tier'], unique=False)
    op.create_index(op.f('ix_scope_items_package_id'), 'scope_items', ['package_id'], unique=False)
    op.create_index(op.f('ix_scope_items_project_id'), 'scope_items', ['project_id'], unique=False)
    op.create_index(op.f('ix_scope_items_run_id'), 'scope_items', ['run_id'], unique=False)
    op.create_table('trade_packages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('package_key', sa.String(length=64), nullable=False),
    sa.Column('package_label', sa.String(length=255), nullable=False),
    sa.Column('csi_divisions', sa.JSON(), nullable=True),
    sa.Column('bundling_rule_source', sa.String(length=16), nullable=False),
    sa.Column('item_count', sa.Integer(), nullable=False),
    sa.Column('bilateral_count', sa.Integer(), nullable=False),
    sa.Column('avg_confidence', sa.Float(), nullable=True),
    sa.Column('narrative_md', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['scope_extraction_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trade_packages_package_key'), 'trade_packages', ['package_key'], unique=False)
    op.create_index(op.f('ix_trade_packages_project_id'), 'trade_packages', ['project_id'], unique=False)
    op.create_index(op.f('ix_trade_packages_run_id'), 'trade_packages', ['run_id'], unique=False)
    op.create_table('bid_exclusions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('bid_document_id', sa.String(length=36), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('source_chunk_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['bid_document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['bid_extraction_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bid_exclusions_bid_document_id'), 'bid_exclusions', ['bid_document_id'], unique=False)
    op.create_index(op.f('ix_bid_exclusions_project_id'), 'bid_exclusions', ['project_id'], unique=False)
    op.create_index(op.f('ix_bid_exclusions_run_id'), 'bid_exclusions', ['run_id'], unique=False)
    op.create_table('bid_inclusions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('bid_document_id', sa.String(length=36), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('source_chunk_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['bid_document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['bid_extraction_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bid_inclusions_bid_document_id'), 'bid_inclusions', ['bid_document_id'], unique=False)
    op.create_index(op.f('ix_bid_inclusions_project_id'), 'bid_inclusions', ['project_id'], unique=False)
    op.create_index(op.f('ix_bid_inclusions_run_id'), 'bid_inclusions', ['run_id'], unique=False)
    op.create_table('bid_line_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('bid_document_id', sa.String(length=36), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('quantity', sa.String(length=64), nullable=True),
    sa.Column('unit', sa.String(length=16), nullable=True),
    sa.Column('unit_price_usd', sa.Float(), nullable=True),
    sa.Column('total_price_usd', sa.Float(), nullable=True),
    sa.Column('csi_section_guess', sa.String(length=16), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('source_chunk_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['bid_document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['bid_extraction_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bid_line_items_bid_document_id'), 'bid_line_items', ['bid_document_id'], unique=False)
    op.create_index(op.f('ix_bid_line_items_csi_section_guess'), 'bid_line_items', ['csi_section_guess'], unique=False)
    op.create_index(op.f('ix_bid_line_items_project_id'), 'bid_line_items', ['project_id'], unique=False)
    op.create_index(op.f('ix_bid_line_items_run_id'), 'bid_line_items', ['run_id'], unique=False)
    op.create_table('bid_summaries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('bid_document_id', sa.String(length=36), nullable=False),
    sa.Column('vendor_name', sa.String(length=255), nullable=True),
    sa.Column('bid_total_usd', sa.Float(), nullable=True),
    sa.Column('primary_csi_divisions', sa.JSON(), nullable=True),
    sa.Column('line_item_count', sa.Integer(), nullable=False),
    sa.Column('inclusion_count', sa.Integer(), nullable=False),
    sa.Column('exclusion_count', sa.Integer(), nullable=False),
    sa.Column('extraction_cost_usd', sa.Float(), nullable=True),
    sa.Column('extraction_latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['bid_document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['bid_extraction_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bid_summaries_bid_document_id'), 'bid_summaries', ['bid_document_id'], unique=False)
    op.create_index(op.f('ix_bid_summaries_project_id'), 'bid_summaries', ['project_id'], unique=False)
    op.create_index(op.f('ix_bid_summaries_run_id'), 'bid_summaries', ['run_id'], unique=False)
    op.create_table('chunks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('page_id', sa.String(length=36), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('chunk_type', sa.String(length=32), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('contextualized_text', sa.Text(), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.Column('bbox', sa.JSON(), nullable=True),
    sa.Column('embedding', Vector(1024), nullable=True),
    sa.Column('embedded', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['page_id'], ['document_pages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chunks_chunk_type'), 'chunks', ['chunk_type'], unique=False)
    op.create_index(op.f('ix_chunks_document_id'), 'chunks', ['document_id'], unique=False)
    op.create_index(op.f('ix_chunks_page_id'), 'chunks', ['page_id'], unique=False)
    op.create_index(op.f('ix_chunks_project_id'), 'chunks', ['project_id'], unique=False)
    op.create_table('page_extractions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('page_id', sa.String(length=36), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('sheet_number', sa.String(length=64), nullable=True),
    sa.Column('sheet_title', sa.String(length=255), nullable=True),
    sa.Column('discipline', sa.String(length=64), nullable=True),
    sa.Column('drawing_scale', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('raw_response', sa.JSON(), nullable=True),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('extracted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['page_id'], ['document_pages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_page_extractions_discipline'), 'page_extractions', ['discipline'], unique=False)
    op.create_index(op.f('ix_page_extractions_document_id'), 'page_extractions', ['document_id'], unique=False)
    op.create_index(op.f('ix_page_extractions_page_id'), 'page_extractions', ['page_id'], unique=True)
    op.create_index(op.f('ix_page_extractions_sheet_number'), 'page_extractions', ['sheet_number'], unique=False)
    op.create_table('scope_citations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('scope_item_id', sa.String(length=36), nullable=False),
    sa.Column('chunk_id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('sheet_number', sa.String(length=64), nullable=True),
    sa.Column('bbox', sa.JSON(), nullable=True),
    sa.Column('rerank_score', sa.Float(), nullable=True),
    sa.Column('extraction_query', sa.String(length=64), nullable=True),
    sa.Column('excerpt', sa.Text(), nullable=True),
    sa.Column('evidence_type', sa.String(length=32), nullable=True),
    sa.Column('doc_type_at_capture', sa.String(length=64), nullable=True),
    sa.Column('is_link_judge_pass', sa.Boolean(), nullable=True),
    sa.Column('link_judge_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['scope_item_id'], ['scope_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scope_citations_document_id'), 'scope_citations', ['document_id'], unique=False)
    op.create_index(op.f('ix_scope_citations_evidence_type'), 'scope_citations', ['evidence_type'], unique=False)
    op.create_index(op.f('ix_scope_citations_scope_item_id'), 'scope_citations', ['scope_item_id'], unique=False)
    op.create_index(op.f('ix_scope_citations_sheet_number'), 'scope_citations', ['sheet_number'], unique=False)
    op.create_table('scope_conflict_members',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('conflict_id', sa.String(length=36), nullable=False),
    sa.Column('scope_item_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('citation_id', sa.String(length=36), nullable=True),
    sa.Column('is_winner', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conflict_id'], ['scope_conflicts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scope_item_id'], ['scope_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scope_conflict_members_conflict_id'), 'scope_conflict_members', ['conflict_id'], unique=False)
    op.create_index(op.f('ix_scope_conflict_members_scope_item_id'), 'scope_conflict_members', ['scope_item_id'], unique=False)
    op.create_table('trade_package_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('package_id', sa.String(length=36), nullable=False),
    sa.Column('scope_item_id', sa.String(length=36), nullable=False),
    sa.Column('assignment_method', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['package_id'], ['trade_packages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scope_item_id'], ['scope_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trade_package_items_package_id'), 'trade_package_items', ['package_id'], unique=False)
    op.create_index(op.f('ix_trade_package_items_scope_item_id'), 'trade_package_items', ['scope_item_id'], unique=False)
    op.create_table('bid_coverage',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('scope_item_id', sa.String(length=36), nullable=False),
    sa.Column('bid_document_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('matched_line_item_id', sa.String(length=36), nullable=True),
    sa.Column('judge_model', sa.String(length=64), nullable=True),
    sa.Column('evidence_chunk_ids', sa.JSON(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['bid_document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['matched_line_item_id'], ['bid_line_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['bid_extraction_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scope_item_id'], ['scope_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bid_coverage_bid_document_id'), 'bid_coverage', ['bid_document_id'], unique=False)
    op.create_index(op.f('ix_bid_coverage_project_id'), 'bid_coverage', ['project_id'], unique=False)
    op.create_index(op.f('ix_bid_coverage_run_id'), 'bid_coverage', ['run_id'], unique=False)
    op.create_index(op.f('ix_bid_coverage_scope_item_id'), 'bid_coverage', ['scope_item_id'], unique=False)
    op.create_table('extracted_cross_references',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('page_extraction_id', sa.String(length=36), nullable=False),
    sa.Column('target_sheet', sa.String(length=64), nullable=False),
    sa.Column('detail_id', sa.String(length=64), nullable=True),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('bbox', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['page_extraction_id'], ['page_extractions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extracted_cross_references_page_extraction_id'), 'extracted_cross_references', ['page_extraction_id'], unique=False)
    op.create_index(op.f('ix_extracted_cross_references_target_sheet'), 'extracted_cross_references', ['target_sheet'], unique=False)
    op.create_table('extracted_entities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('page_extraction_id', sa.String(length=36), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('bbox', sa.JSON(), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['page_extraction_id'], ['page_extractions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extracted_entities_entity_type'), 'extracted_entities', ['entity_type'], unique=False)
    op.create_index(op.f('ix_extracted_entities_page_extraction_id'), 'extracted_entities', ['page_extraction_id'], unique=False)
    op.create_table('extracted_notes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('page_extraction_id', sa.String(length=36), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('bbox', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['page_extraction_id'], ['page_extractions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extracted_notes_page_extraction_id'), 'extracted_notes', ['page_extraction_id'], unique=False)
    op.create_table('extracted_schedules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('page_extraction_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('columns', sa.JSON(), nullable=False),
    sa.Column('rows', sa.JSON(), nullable=False),
    sa.Column('bbox', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['page_extraction_id'], ['page_extractions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extracted_schedules_page_extraction_id'), 'extracted_schedules', ['page_extraction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_extracted_schedules_page_extraction_id'), table_name='extracted_schedules')
    op.drop_table('extracted_schedules')
    op.drop_index(op.f('ix_extracted_notes_page_extraction_id'), table_name='extracted_notes')
    op.drop_table('extracted_notes')
    op.drop_index(op.f('ix_extracted_entities_page_extraction_id'), table_name='extracted_entities')
    op.drop_index(op.f('ix_extracted_entities_entity_type'), table_name='extracted_entities')
    op.drop_table('extracted_entities')
    op.drop_index(op.f('ix_extracted_cross_references_target_sheet'), table_name='extracted_cross_references')
    op.drop_index(op.f('ix_extracted_cross_references_page_extraction_id'), table_name='extracted_cross_references')
    op.drop_table('extracted_cross_references')
    op.drop_index(op.f('ix_bid_coverage_scope_item_id'), table_name='bid_coverage')
    op.drop_index(op.f('ix_bid_coverage_run_id'), table_name='bid_coverage')
    op.drop_index(op.f('ix_bid_coverage_project_id'), table_name='bid_coverage')
    op.drop_index(op.f('ix_bid_coverage_bid_document_id'), table_name='bid_coverage')
    op.drop_table('bid_coverage')
    op.drop_index(op.f('ix_trade_package_items_scope_item_id'), table_name='trade_package_items')
    op.drop_index(op.f('ix_trade_package_items_package_id'), table_name='trade_package_items')
    op.drop_table('trade_package_items')
    op.drop_index(op.f('ix_scope_conflict_members_scope_item_id'), table_name='scope_conflict_members')
    op.drop_index(op.f('ix_scope_conflict_members_conflict_id'), table_name='scope_conflict_members')
    op.drop_table('scope_conflict_members')
    op.drop_index(op.f('ix_scope_citations_sheet_number'), table_name='scope_citations')
    op.drop_index(op.f('ix_scope_citations_scope_item_id'), table_name='scope_citations')
    op.drop_index(op.f('ix_scope_citations_evidence_type'), table_name='scope_citations')
    op.drop_index(op.f('ix_scope_citations_document_id'), table_name='scope_citations')
    op.drop_table('scope_citations')
    op.drop_index(op.f('ix_page_extractions_sheet_number'), table_name='page_extractions')
    op.drop_index(op.f('ix_page_extractions_page_id'), table_name='page_extractions')
    op.drop_index(op.f('ix_page_extractions_document_id'), table_name='page_extractions')
    op.drop_index(op.f('ix_page_extractions_discipline'), table_name='page_extractions')
    op.drop_table('page_extractions')
    op.drop_index(op.f('ix_chunks_project_id'), table_name='chunks')
    op.drop_index(op.f('ix_chunks_page_id'), table_name='chunks')
    op.drop_index(op.f('ix_chunks_document_id'), table_name='chunks')
    op.drop_index(op.f('ix_chunks_chunk_type'), table_name='chunks')
    op.drop_table('chunks')
    op.drop_index(op.f('ix_bid_summaries_run_id'), table_name='bid_summaries')
    op.drop_index(op.f('ix_bid_summaries_project_id'), table_name='bid_summaries')
    op.drop_index(op.f('ix_bid_summaries_bid_document_id'), table_name='bid_summaries')
    op.drop_table('bid_summaries')
    op.drop_index(op.f('ix_bid_line_items_run_id'), table_name='bid_line_items')
    op.drop_index(op.f('ix_bid_line_items_project_id'), table_name='bid_line_items')
    op.drop_index(op.f('ix_bid_line_items_csi_section_guess'), table_name='bid_line_items')
    op.drop_index(op.f('ix_bid_line_items_bid_document_id'), table_name='bid_line_items')
    op.drop_table('bid_line_items')
    op.drop_index(op.f('ix_bid_inclusions_run_id'), table_name='bid_inclusions')
    op.drop_index(op.f('ix_bid_inclusions_project_id'), table_name='bid_inclusions')
    op.drop_index(op.f('ix_bid_inclusions_bid_document_id'), table_name='bid_inclusions')
    op.drop_table('bid_inclusions')
    op.drop_index(op.f('ix_bid_exclusions_run_id'), table_name='bid_exclusions')
    op.drop_index(op.f('ix_bid_exclusions_project_id'), table_name='bid_exclusions')
    op.drop_index(op.f('ix_bid_exclusions_bid_document_id'), table_name='bid_exclusions')
    op.drop_table('bid_exclusions')
    op.drop_index(op.f('ix_trade_packages_run_id'), table_name='trade_packages')
    op.drop_index(op.f('ix_trade_packages_project_id'), table_name='trade_packages')
    op.drop_index(op.f('ix_trade_packages_package_key'), table_name='trade_packages')
    op.drop_table('trade_packages')
    op.drop_index(op.f('ix_scope_items_run_id'), table_name='scope_items')
    op.drop_index(op.f('ix_scope_items_project_id'), table_name='scope_items')
    op.drop_index(op.f('ix_scope_items_package_id'), table_name='scope_items')
    op.drop_index(op.f('ix_scope_items_evidence_tier'), table_name='scope_items')
    op.drop_index(op.f('ix_scope_items_csi_division'), table_name='scope_items')
    op.drop_index(op.f('ix_scope_items_csi_code'), table_name='scope_items')
    op.drop_table('scope_items')
    op.drop_index(op.f('ix_scope_gaps_status'), table_name='scope_gaps')
    op.drop_index(op.f('ix_scope_gaps_severity'), table_name='scope_gaps')
    op.drop_index(op.f('ix_scope_gaps_run_id'), table_name='scope_gaps')
    op.drop_index(op.f('ix_scope_gaps_project_id'), table_name='scope_gaps')
    op.drop_index(op.f('ix_scope_gaps_gap_type'), table_name='scope_gaps')
    op.drop_index(op.f('ix_scope_gaps_csi_division'), table_name='scope_gaps')
    op.drop_table('scope_gaps')
    op.drop_index(op.f('ix_scope_conflicts_status'), table_name='scope_conflicts')
    op.drop_index(op.f('ix_scope_conflicts_run_id'), table_name='scope_conflicts')
    op.drop_index(op.f('ix_scope_conflicts_project_id'), table_name='scope_conflicts')
    op.drop_index(op.f('ix_scope_conflicts_csi_division'), table_name='scope_conflicts')
    op.drop_index(op.f('ix_scope_conflicts_conflict_type'), table_name='scope_conflicts')
    op.drop_table('scope_conflicts')
    op.drop_index(op.f('ix_document_pages_document_id'), table_name='document_pages')
    op.drop_table('document_pages')
    op.drop_index(op.f('ix_bid_extraction_runs_scope_run_id'), table_name='bid_extraction_runs')
    op.drop_index(op.f('ix_bid_extraction_runs_project_id'), table_name='bid_extraction_runs')
    op.drop_table('bid_extraction_runs')
    op.drop_index(op.f('ix_trade_division_relevance_project_id'), table_name='trade_division_relevance')
    op.drop_index(op.f('ix_trade_division_relevance_csi_division'), table_name='trade_division_relevance')
    op.drop_table('trade_division_relevance')
    op.drop_index(op.f('ix_scope_extraction_runs_project_id'), table_name='scope_extraction_runs')
    op.drop_table('scope_extraction_runs')
    op.drop_index(op.f('ix_project_profiles_project_id'), table_name='project_profiles')
    op.drop_table('project_profiles')
    op.drop_index(op.f('ix_documents_vendor_name'), table_name='documents')
    op.drop_index(op.f('ix_documents_source'), table_name='documents')
    op.drop_index(op.f('ix_documents_sha256'), table_name='documents')
    op.drop_index(op.f('ix_documents_project_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_canonical_vendor'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_audit_log_run_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_project_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_entity_type'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_entity_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_created_at'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_action'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_table('projects')
    op.drop_index(op.f('ix_llm_calls_project_id'), table_name='llm_calls')
    op.drop_index(op.f('ix_llm_calls_page_extraction_id'), table_name='llm_calls')
    op.drop_index(op.f('ix_llm_calls_document_id'), table_name='llm_calls')
    op.drop_table('llm_calls')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
