"""P2: sheet_revisions table (W18 mitigation)

Revision ID: 94fbaabf4cf3
Revises: 0997ae283649
Create Date: 2026-05-06 00:47:03.185035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94fbaabf4cf3'
down_revision: Union[str, Sequence[str], None] = '0997ae283649'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sheet_revisions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('page_extraction_id', sa.String(length=36), nullable=True),
    sa.Column('sheet_id', sa.String(length=64), nullable=False),
    sa.Column('rev_number', sa.String(length=16), nullable=False),
    sa.Column('rev_date', sa.String(length=32), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('by', sa.String(length=64), nullable=True),
    sa.Column('rev_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['page_extraction_id'], ['page_extractions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sheet_revisions_document_id'), 'sheet_revisions', ['document_id'], unique=False)
    op.create_index(op.f('ix_sheet_revisions_page_extraction_id'), 'sheet_revisions', ['page_extraction_id'], unique=False)
    op.create_index(op.f('ix_sheet_revisions_project_id'), 'sheet_revisions', ['project_id'], unique=False)
    op.create_index(op.f('ix_sheet_revisions_sheet_id'), 'sheet_revisions', ['sheet_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sheet_revisions_sheet_id'), table_name='sheet_revisions')
    op.drop_index(op.f('ix_sheet_revisions_project_id'), table_name='sheet_revisions')
    op.drop_index(op.f('ix_sheet_revisions_page_extraction_id'), table_name='sheet_revisions')
    op.drop_index(op.f('ix_sheet_revisions_document_id'), table_name='sheet_revisions')
    op.drop_table('sheet_revisions')
    # ### end Alembic commands ###
