"""P5 — add qty_value + qty_uom on scope_items

Revision ID: dc6326abf1e7
Revises: bb7c045d3a19
Create Date: 2026-05-06 02:12:20.852953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc6326abf1e7'
down_revision: Union[str, Sequence[str], None] = 'bb7c045d3a19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scope_items', sa.Column('qty_value', sa.Float(), nullable=True))
    op.add_column('scope_items', sa.Column('qty_uom', sa.String(length=16), nullable=True))
    op.create_index(op.f('ix_scope_items_qty_uom'), 'scope_items', ['qty_uom'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scope_items_qty_uom'), table_name='scope_items')
    op.drop_column('scope_items', 'qty_uom')
    op.drop_column('scope_items', 'qty_value')
    # ### end Alembic commands ###
