"""P3: symbol_legend table (W3 mitigation)

Revision ID: ea8af2591b08
Revises: 94fbaabf4cf3
Create Date: 2026-05-06 00:58:14.392502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea8af2591b08'
down_revision: Union[str, Sequence[str], None] = '94fbaabf4cf3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('symbol_legend',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('page_extraction_id', sa.String(length=36), nullable=True),
    sa.Column('symbol_glyph', sa.String(length=64), nullable=False),
    sa.Column('meaning', sa.Text(), nullable=False),
    sa.Column('discipline', sa.String(length=32), nullable=True),
    sa.Column('source_sheet_id', sa.String(length=64), nullable=True),
    sa.Column('csi_section_hint', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['page_extraction_id'], ['page_extractions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_symbol_legend_discipline'), 'symbol_legend', ['discipline'], unique=False)
    op.create_index(op.f('ix_symbol_legend_document_id'), 'symbol_legend', ['document_id'], unique=False)
    op.create_index(op.f('ix_symbol_legend_page_extraction_id'), 'symbol_legend', ['page_extraction_id'], unique=False)
    op.create_index(op.f('ix_symbol_legend_project_id'), 'symbol_legend', ['project_id'], unique=False)
    op.create_index(op.f('ix_symbol_legend_symbol_glyph'), 'symbol_legend', ['symbol_glyph'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_symbol_legend_symbol_glyph'), table_name='symbol_legend')
    op.drop_index(op.f('ix_symbol_legend_project_id'), table_name='symbol_legend')
    op.drop_index(op.f('ix_symbol_legend_page_extraction_id'), table_name='symbol_legend')
    op.drop_index(op.f('ix_symbol_legend_document_id'), table_name='symbol_legend')
    op.drop_index(op.f('ix_symbol_legend_discipline'), table_name='symbol_legend')
    op.drop_table('symbol_legend')
    # ### end Alembic commands ###
